- name: loops
  hosts: all
  tasks:
    - name: fruit name
      ansible.builtin.debug:
       msg : Fruit Name = {{ item }}
      loop:
       - bananna
       - apple
    - name: fruit name with quantity
      ansible.builtin.debug:
        msg: Fruit Name = {{ item.name }}, Quantity = {{ item.qty }}
      loop:
          - { name: bananna, qty: 100 }
          - { name: apple, qty: 200 }








