- name: Demo play on vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}

- name: Demo play on vars
  hosts: all
  vars_files:
    demo.vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}

