- name: Demo play on vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}

- name: Demo play on vars
  hosts: all
  vars_files:
    demo.vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}
- name: Demo on task level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}
      #vars_files
      vars:
        URL: task.example.com
- name: Read the variable from inventory file
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}


